### ISSUE TITLE
piltide ja tekstide otsimine kuue sündmuse jaoks

### ISSUE THREAD

**Issue by terjevolke** [jasper-tambur/portfoolioprojekt#10]

**Comment by N4thanT** [comment]
![image](https://user-images.githubusercontent.com/93092615/140289698-a5ac67d2-d84c-4f52-ba66-a683045b86d7.png)

Film tuli välja aastal 2003 ja on ilmselt kõige tuntuim film kus Johnny Depp starib. Produtseeritud Jerry Bruckheimer poolt, Kariibi mere piraadid on baseeritud Walt Disney seikluspargi sõidu pealt, millel on sama nimi filmiga. 

Lugu jälgib Jack Sparrowt ja Will Turnerit oma ülesandel leida Elizabeth Swann, kes on Will-i elu arm ja kuberneri tütar. Ta rööviti ära hirmsa Captin Barbossa poolt, kes koos oma meeskonnaga on ära neetud, et mitte elada aga et mitte ka surra. Aga nad saavad needust murda kui neil on vere ohverdus. 

![image](https://user-images.githubusercontent.com/93092615/140289822-ffef1a66-9c07-4be0-a903-cb430130c1b7.png)

A Nightmare on Elm Street on 1984 ameerika üleloomulik slasher film kirjutatud ja juhendatud Wes Craveni poolt ning, produtseeritud Robert Shaye poolt. See on esimene osa A Nightmare on Elm Street frantsiisis ja on Johnny Deppi filmidebüüt. 

Lugu järgib nelja teismelist kes elavad ühel tänaval väljamõeldud külas, Springwood Ohios. Neid rünnatakse ja tapetakse oma unenägudes põlenud mehe poolt nimega Fred Kruger kes kannab nahast kinnast, mis põhjustab nende surma ka päris elus. Peategelane Nancy peab kiirelt mõtlema samas kui Fred üritab neid maha võtta üks, ühe järgi. 

![image](https://user-images.githubusercontent.com/93092615/140289941-9232c1e6-b109-472b-9ee7-e9b07252eb73.png)

Murder on the Orient Express on 2017 mõrva müsteerium film juhendatud Kenneth Branaghi poolt, baseeritud 1934 aasta romaanil millel on sama nimi kui filmil, kirjutatud Agatha Christie poolt. Film on Christie romaani neljas ekraniseering, mis järgneb 1974. aasta filmile, 2001. aasta telefilmi versioonile ja 2010. aasta telesarja Agatha Christie Poirot episoodile. 

Hercule Poirot, maailma parim detektiiv, otsustab reisida Orient Expressiga. Rong jääb kogemata väikese laviini tõttu seisma. Aga varsti tuli välja, et keegi oli kavandanud mõrva ja peab nüüd välja uurima kes on mõrvar.

![image](https://user-images.githubusercontent.com/93092615/140290018-537a69f6-b461-49d6-91da-d00d54905381.png)

Fantastic Beasts and Where to Find Them on 2016. aasta fantaasiafilm, mille režissöör on David Yates. Briti ja Ameerika ühistoodang, see on Harry Potteri filmisarja järellugu ja eellugu. Selle produtseeris ja kirjutas J. K. Rowling oma stsenaristidebüüdil, inspireerituna tema 2001. aasta samanimelisest "juhendist". 

Samal ajal kui New York City terroriseerib kummaline tume jõud, palub Briti magizoloog Newt Scamander mittemaagilise Jacobi abi, et koguda kokku põgenenud maagilised olendid.

**Comment by N4thanT** [comment]
https://images.genial.ly/5daec9d80436800f6be2bb02/a0c21ef8-1f97-4fdd-ac46-45f74c3416e6.jpeg  

Charlie ja šokolaadivabrik on 2005. aastal valminud muusikaline fantaasiafilm, mille lavastas Tim Burton ja kirjutas John August, mis põhineb Roald Dahli 1964. aasta samanimelisel Briti romaanil. 

Vaesunud perest pärit noor poiss Charlie ja veel neli last võidavad ringkäigu hämmastavasse šokolaadivabrikusse, mida juhib fantaasiarikas šokolaadimeister Willy Wonka ja tema Oompa-Loompase töötajad. 

https://images.indianexpress.com/2016/07/alice-in-wonderland-main_759.jpg

Alice Imedemaal on 2010. aasta Ameerika tume fantaasiafilm, mille režissöör on Tim Burton, Linda Woolvertoni kirjutatud stsenaariumi põhjal, inspireeritud Lewis Carrolli fantaasiaromaanidest. Alice in Wonderland produtseeris Walt Disney Pictures ning filmiti Ühendkuningriigis ja USA-s. See on ka 2010. aasta suuruselt teine film. 

Alice, tagasihoidlik ja individuaalne 19-aastane noorneid, kes on kihlatud Inglise aadliku pätiga. Kihluspeol põgeneb ta rahva hulgast, et kaaluda, kas abielluda, ja kukub aia auku, kui märkas ebaharilikku jänest. Saabudes kummalisse ja sürreaalsesse kohta nimega "Underland",  mis meenutab lapsepõlves nähtud õudusunenägusid. Alice mõistab, et ta on siin põhjusega, et vallutada kohutav Jabberwocky ja taastada õiguspärane kuninganna oma troonile.

**Comment by N4thanT** [comment]
![image](https://user-images.githubusercontent.com/93092615/140313475-4686a966-bb96-4d37-bf74-998cd5271739.png)

Charlie ja šokolaadivabrik on 2005. aastal valminud muusikaline fantaasiafilm, mille lavastas Tim Burton ja kirjutas John August, mis põhineb Roald Dahli 1964. aasta samanimelisel Briti romaanil. 

Vaesunud perest pärit noor poiss Charlie ja veel neli last võidavad ringkäigu hämmastavasse šokolaadivabrikusse, mida juhib fantaasiarikas šokolaadimeister Willy Wonka ja tema Oompa-Loompase töötajad. 

![image](https://user-images.githubusercontent.com/93092615/140313443-03cf64e6-ba4f-443a-9bff-66ae5dad1168.png)

Alice Imedemaal on 2010. aasta Ameerika tume fantaasiafilm, mille režissöör on Tim Burton, Linda Woolvertoni kirjutatud stsenaariumi põhjal, inspireeritud Lewis Carrolli fantaasiaromaanidest. Alice in Wonderland produtseeris Walt Disney Pictures ning filmiti Ühendkuningriigis ja USA-s. See on ka 2010. aasta suuruselt teine film. 

Alice, tagasihoidlik ja individuaalne 19-aastane noorneid, kes on kihlatud Inglise aadliku pätiga. Kihluspeol põgeneb ta rahva hulgast, et kaaluda, kas abielluda, ja kukub aia auku, kui märkas ebaharilikku jänest. Saabudes kummalisse ja sürreaalsesse kohta nimega "Underland",  mis meenutab lapsepõlves nähtud õudusunenägusid. Alice mõistab, et ta on siin põhjusega, et vallutada kohutav Jabberwocky ja taastada õiguspärane kuninganna oma troonile.
